services:

  # Springboot
  service:
    container_name: watabaseh-service
    image: service:latest
    restart: on-failure
    build: .
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      - database

  # MySql
  database:
    container_name: watabaseh-database
    image: arm64v8/mysql:oracle
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: watabaseh
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  # Liquibase
  liquibase:
    container_name: watabaseh-liquibase
    image: liquibase/liquibase
    platform: linux/arm64/v8
    command: --defaultsFile=./changelog/liquibase.properties update
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
      - ./liquibase/scripts:/liquibase/scripts
    depends_on:
      - database
