services:

  # Springboot
  web:
    container_name: watabaseh-service
    image: watabaseh/springboot:latest
    restart: on-failure
    build: .
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy

  # MySql
  database:
    container_name: watabaseh-database
    image: arm64v8/mysql:oracle
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: watabaseh
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      retries: 10
      timeout: 10s
      interval: 1s

  # Liquibase
  liquibase:
    container_name: watabaseh-liquibase
    image: liquibase/liquibase
    command: --defaultsFile=/liquibase/liquibase.docker.properties update
    environment:
      - INSTALL_MYSQL=true
    volumes:
      - ./liquibase/liquibase.docker.properties:/liquibase/liquibase.docker.properties
      - ./liquibase/changelog:/liquibase/changelog
      - ./liquibase/scripts:/liquibase/scripts
    depends_on:
      database:
        condition: service_healthy
