services:

  service:
    container_name: watabaseh-service
    build: .
    image: service:latest
    restart: on-failure
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      - database

  database:
    container_name: watabaseh-database
    image: mysql:latest
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: watabaseh
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password